"""
ComfyUI API 客户端（v2 / 2026-09 修复版）
- 角色：Qwen 2512 生成基础图 → Qwen Edit 2511 生成多视图（正面/左侧/右侧/背面）
- 物品：Qwen 2512 生成基础图 → Qwen Edit 2511 生成 3D 多视角（正面/左45°/右45°/俯视）
- 场景：Qwen 2512 生成基础图 → Qwen Edit 2511 生成 3D 多视角（正面/左45°/右45°/俯视）
- 视频：MiniMax H3（Ref2VA）10 段无缝生成

v2 关键修复：
1. UI(node-graph) → API 转换改为「节点自带 widgets_values_named 优先」，
   仅在缺失时按 object_info 声明的控件顺序做位置兜底（并剔除 control_after_generate
   等前端伪控件），彻底解决 KSampler 参数错位（steps='randomize'）。
2. 展开 ComfyUI 新版 subgraph（UUID 型 class_type 实例）：把子图内部真实节点
   抽取为 API 节点，并把 SetNode/GetNode/Reroute 走通为「值来源重定向」。
3. 过滤 MarkdownNote / Note / Label / Reroute / PrimitiveNode 等虚拟节点。
4. 多视角：3 个 LoadImageOutput 参考图全部替换（原实现只改第一个）。
5. 视频：前端 HTTP 资源路径解析为本地绝对路径；H3 的 10 段 Text Multiline
   全部替换（原实现只改第一段），并按 clip 序号一一对应。
"""
import os
import re
import json
import time
import copy
import shutil
import logging
import threading
import requests
from typing import Dict, List, Optional, Any, Tuple

from config import (
    COMFYUI_URL, COMFYUI_WORKFLOWS_DIR, COMFYUI_OUTPUT_DIR,
    PROJECT_OUTPUT_DIR, WORKFLOW_TEMPLATE, MULTIVIEW_CONFIG,
    H3_EMIT_AUDIO,
    CONFLICT_NEGATIVE_TOKENS,
)
from dialogue_utils import (dialogue_text as _dlg_text, format_line as _dlg_line,
                            dialogue_speaker as _dlg_speaker)
from h3_episode_builder import H3EpisodeBuilder

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ===================== 调用统计（P2-3 成本看板数据源） =====================
# 只做进程内累计计数，不落盘、不影响业务；analytics 模块按需读取。
_CALL_STATS = {
    "prompt_submitted": 0,      # 提交到 /prompt 的次数
    "prompt_failed": 0,         # 提交失败次数
    "completed": 0,             # 等待完成的次数（成功）
    "waited_seconds": 0.0,      # 累计等待时长（GPU 在跑的时间近似值）
    "segments_generated": 0,    # 累计生成段数（视频）
}
_CALL_STATS_LOCK = threading.Lock()


def get_call_stats() -> dict:
    """读取调用统计快照"""
    return dict(_CALL_STATS)


def reset_call_stats() -> dict:
    """重置调用统计"""
    for k in list(_CALL_STATS.keys()):
        _CALL_STATS[k] = 0 if not isinstance(_CALL_STATS[k], float) else 0.0
    return dict(_CALL_STATS)


def _bump(key: str, delta=1) -> None:
    """安全累加统计项（统计失败绝不影响业务）"""
    try:
        _CALL_STATS[key] = _CALL_STATS.get(key, 0) + delta
    except Exception:  # noqa: BLE001
        pass

# 前端伪控件 / 虚拟节点（不应提交给后端）
PSEUDO_WIDGETS = {
    "upload", "refresh", "Constant",
    "Auto-refresh after generation", "control_after_generate_widget",
}
# 位置兜底时需要剔除的「执行后动作」取值（跟随在 seed 之后）
PSEUDO_VALUES = {"fixed", "increment", "decrement", "randomize"}
# 需要跳过的虚拟节点类型
VIRTUAL_NODE_TYPES = {
    "MarkdownNote", "Note", "Label (rgthree)", "Reroute", "PrimitiveNode", "Bookmark",
}
# 正向提示词判定：出现这些词视为负向提示词
NEGATIVE_HINTS = ("模糊", "水印", "blurry", "watermark", "low quality", "worst quality", "低质量", "噪点")

# C 项⑧：图片链路**彻底无水印**（不修改 ComfyUI 工作流文件，仅在本模块提交前对内存中的
# API prompt 做强化）：
#   1) 正向提示词统一追加「无水印/无文字」声明；
#   2) 负向提示词统一追加水印类排除词。
# 说明：项目内 4 个图片工作流（角色/物品/场景/分镜生成.json）经核查**不含任何水印/文字叠加
# 节点**，水印只可能由模型自行"画"出来，因此从提示词侧双向压制是彻底去水印的必要手段。
NO_WATERMARK_POSITIVE_SUFFIX = ("。画面干净：不含任何水印、logo、签名、日期戳、字幕、标题文字、版权标识，"
                                "尤其不得出现「AI生成」等任何生成标识文字（含右下角）")
NO_WATERMARK_NEGATIVE_EXTRA = ("水印, watermark, logo, 标志, 签名, 签字, 日期戳, 时间戳, "
                               "文字, 字幕, 标题文字, 版权标识, 边框水印, 半透明水印, "
                               "AI生成, AI生成字样, 生成标识, 机器生成, generated by AI")

# H3 视频链路：画面内文字/字幕压制（H3 提示词节点为纯文本节点 Text Multiline）
VIDEO_NO_TEXT_SUFFIX = ("。画面中不得出现任何文字、字幕、台词文本、标题、水印、logo 或标识，"
                        "尤其不得在画面底部、顶部或右下角绘制台词字幕与生成标识")
VIDEO_PROMPT_NODE_TYPES = ("Text Multiline", "Text", "CLIPTextEncode", "PrimitiveStringMultiline")

# 分镜图景别强约束：仅写「特写」二字时模型容易退化为中景/近景，这里给出显式构图规范
SHOT_CAMERA_SPECS = {
    "特写": ("特写镜头（close-up）：镜头极贴近主体，人物面部（或手部、道具局部）占据画面 70% 以上面积，"
             "背景明显虚化，只呈现局部，严禁退为近景、中景或全景"),
    "近景": ("近景镜头（medium close-up）：取景自人物胸部以上至头顶，面部细节清晰，"
             "严禁退为中景或全景"),
    "中景": ("中景镜头（medium shot）：取景自人物腰部或膝部以上至头顶，人物占画面一半左右，"
             "可带入部分环境"),
    "全景": "全景镜头（wide shot）：完整呈现人物全身及其所处环境，人物占画面高度的大半",
    "远景": "远景镜头（long shot）：人物在画面中较小、环境为主体，强调空间感与氛围",
}
SHOT_ACTION_SUFFIX = ("；上述动作必须完整、明确地表现出来（动作结果一眼可辨，如道具已收起、已离开手部），"
                      "不得省略、弱化或只做出起始姿态")
# 提示词所在字段（CLIPTextEncode.text / TextEncodeQwenImageEditPlus.prompt）
PROMPT_TEXT_FIELDS = ("text", "prompt")
# 需要剥离的 LoadImage* 前端显示后缀
SUFFIX_RE = re.compile(r"\s*\[(output|input|temp)\]\s*$")

# ===================== P0 修复：正负提示词冲突 / 场景资产带人 / 画幅统一 =====================

# 1) 正负提示词冲突：按长度降序匹配，保证「3D渲染」先于「3D」被命中
CONFLICT_NEGATIVE_SORTED = tuple(sorted(CONFLICT_NEGATIVE_TOKENS, key=len, reverse=True))

# 2) 场景资产禁止出现人物：
#    场景定义里常带「村民三两结伴」这类人物描述，会直接渲染出人（实测"山间小径"资产图 4 人）。
#    正向追加空场景声明 + 生成前清洗掉人物描述短语。
SCENE_NO_CHARACTER_SUFFIX = (
    "。空场景：画面中不得出现任何人物、人影、人群、士兵或生物，"
    "只呈现环境本身（建筑、地形、植被、道具与光影）"
)
# 人物类词汇（两字及以上，避免误伤"人间仙境/人迹罕至"等场景词）
CHARACTER_WORDS = (
    "人物", "角色", "主角", "村民", "人群", "人们", "众人", "行人", "路人", "群众", "游客", "游人",
    "士兵", "侍卫", "侍从", "仆人", "仆役", "孩童", "孩子", "小孩", "老者", "老人", "青年", "少女",
    "少年", "男子", "女子", "人影", "身影", "侠客", "武者", "修士", "商贩", "摊贩", "渔夫", "农夫",
    "僧人", "道士", "骑士", "守卫", "弟子", "随从", "观众", "看客", "陌生人", "男女老少",
    "人山人海", "三三两两", "结伴", "成群结队", "熙熙攘攘", "往来穿梭", "人头攒动",
)
# 数量+人（如"4人""四个人""几人群"）
CHARACTER_QTY_RE = re.compile(
    r"[0-9０-９一二三四五六七八九十两几数多]+\s*(?:个|名|位|群|队|对)?\s*(?:人|人物|人影|身影)"
)
# 提示词分句符（按句清洗，人物句整句丢弃）
_PROMPT_SPLIT_RE = re.compile(r"[，,；;。\n]")

# 目录标注（P0-5 修复）：
#   LoadImageOutput / LoadAudioOutput / LoadVideoOutput 等「Output 系列」读取 ComfyUI
#   output 目录，写入的 image/audio/video 值必须带 " [output]" 标注，否则 ComfyUI 的
#   folder_paths.exists_annotated_filepath() 会回退到 input 目录查找并报
#   400 "Invalid image file"。
#   LoadImage / LoadAudio / LoadVideo 等读取 input 目录，禁止带标注。
ANNOTATED_DIR = "output"
OUTPUT_LOAD_CLASSES = {"LoadImageOutput", "LoadAudioOutput", "LoadVideoOutput",
                       "LoadLatentOutput", "LoadImageMaskOutput"}
INPUT_LOAD_CLASSES = {"LoadImage", "LoadAudio", "LoadVideo", "LoadImageMask",
                      "LoadAnimatedImage", "LoadLatent"}
# 文件名型（媒体）输入键：转换时需按节点类型规范化目录标注
MEDIA_INPUT_KEYS = {"image", "images", "audio", "video", "file", "filename", "path",
                    "image_path", "audio_path", "video_path"}


class ComfyUIClient:
    """ComfyUI API 客户端"""

    def __init__(self, base_url: str = COMFYUI_URL):
        self.base_url = base_url.rstrip("/")
        self.client_id = self._generate_client_id()
        self._object_info = None
        self._object_info_ts = 0.0
        self.last_convert_meta: Dict[str, Any] = {}

    def _generate_client_id(self) -> str:
        import uuid
        return str(uuid.uuid4())

    # ===================== 基础 HTTP =====================

    def _get(self, path: str, timeout: int = 30) -> Any:
        resp = requests.get(f"{self.base_url}{path}", timeout=timeout)
        resp.raise_for_status()
        return resp.json()

    def _post(self, path: str, data: dict = None) -> Any:
        resp = requests.post(f"{self.base_url}{path}", json=data or {}, timeout=300)
        resp.raise_for_status()
        return resp.json()

    def get_status(self, timeout: int = 3) -> dict:
        """探测 ComfyUI 在线状态。

        注意：这是高频调用的状态接口（前端每次刷新都会打），
        因此**必须用短超时**——默认 3 秒。用 requests 的 (connect, read) 元组形式，
        保证「主机不可达时快速失败」而不是干等 30 秒（Windows 上防火墙丢包会更久）。
        """
        try:
            resp = requests.get(f"{self.base_url}/system_stats",
                                timeout=(min(2, timeout), timeout))
            resp.raise_for_status()
            return {"status": "online", "stats": resp.json()}
        except Exception as e:
            return {"status": "offline", "error": str(e)}

    def get_object_info(self, force: bool = False, ttl: int = 300) -> dict:
        """获取 /object_info（带缓存，离线时返回空 dict，不影响主流程）"""
        now = time.time()
        if not force and self._object_info is not None and (now - self._object_info_ts) < ttl:
            return self._object_info
        try:
            self._object_info = self._get("/object_info", timeout=60)
            self._object_info_ts = now
        except Exception as e:
            logger.warning(f"获取 object_info 失败（将跳过严格校验）: {e}")
            if self._object_info is None:
                self._object_info = {}
        return self._object_info

    def declared_inputs(self, class_type: str) -> List[str]:
        """按 object_info 声明顺序返回节点可声明的输入名（required 在前，optional 在后）"""
        oi = self.get_object_info().get(class_type) or {}
        spec = oi.get("input") or {}
        names = list((spec.get("required") or {}).keys()) + list((spec.get("optional") or {}).keys())
        return names

    # ===================== 工作流加载与转换 =====================

    def load_workflow(self, workflow_file: str, return_meta: bool = False):
        """加载工作流文件并转换为 API prompt 格式"""
        workflow_path = os.path.join(COMFYUI_WORKFLOWS_DIR, workflow_file)
        with open(workflow_path, "r", encoding="utf-8-sig") as f:   # 兼容 UTF-8 BOM
            wf = json.load(f)
        return self.to_api(wf, return_meta=return_meta)

    @staticmethod
    def _is_api_format(wf: dict) -> bool:
        if not isinstance(wf, dict) or not wf:
            return False
        if "nodes" in wf or "links" in wf:
            return False
        return all(isinstance(v, dict) and "class_type" in v for v in wf.values())

    def to_api(self, wf: dict, return_meta: bool = False):
        """UI(node-graph) → API prompt"""
        if self._is_api_format(wf):
            meta = {"already_api": True, "node_count": len(wf)}
            return (wf, meta) if return_meta else wf
        api, meta = self._ui_to_api(wf)
        self.last_convert_meta = meta
        return (api, meta) if return_meta else api

    # ---------- 核心转换 ----------

    @staticmethod
    def _link_specs(links, prefix: str) -> Dict[Any, Tuple[str, int]]:
        """link 列表 → {link_id: ('node', 扁平节点id, 输出槽位)}"""
        out: Dict[Any, Tuple[str, int]] = {}
        for l in links or []:
            if isinstance(l, dict):
                lid, oid, oslot = l.get("id"), l.get("origin_id"), l.get("origin_slot", 0)
            elif isinstance(l, (list, tuple)) and len(l) >= 3:
                lid, oid, oslot = l[0], l[1], l[2]
            else:
                continue
            if lid is None or oid is None:
                continue
            out[lid] = ("node", f"{prefix}{oid}", oslot)
        return out

    def _ui_to_api(self, ui_workflow: dict) -> Tuple[dict, dict]:
        subgraphs: Dict[str, dict] = {}
        for sg in ((ui_workflow.get("definitions") or {}).get("subgraphs") or []):
            if sg.get("id"):
                subgraphs[sg["id"]] = sg

        flat: Dict[str, dict] = {}            # 扁平真实节点: id -> {type, named, seq}
        pending: List[tuple] = []             # (节点id, 输入名, 取值 spec)
        redirect: Dict[tuple, tuple] = {}      # (节点id, 槽位) -> spec（含 GetNode/Reroute/子图输出）
        set_map: Dict[str, tuple] = {}         # SetNode 名 -> spec
        inst_records: List[tuple] = []         # (顺序, clip号, 实例id, prompt 的 spec)
        warnings: List[str] = []
        seq = [0]

        def walk(nodes, links, prefix, depth, in_bindings, in_link_names, in_slot_names,
                 inode, onode):
            link_spec = self._link_specs(links, prefix)
            out_alias: Dict[int, tuple] = {}

            for raw in nodes or []:
                nid = raw.get("id")
                ntype = raw.get("type") or ""
                fid = f"{prefix}{nid}"
                named = dict(raw.get("widgets_values_named") or {})

                # 1) 子图实例（UUID 型 class_type）→ 递归展开
                sg = subgraphs.get(ntype)
                if sg and depth < 6:
                    inst_in: Dict[str, tuple] = {}
                    for inp in raw.get("inputs") or []:
                        nm, lid = inp.get("name"), inp.get("link")
                        if lid is not None and lid in link_spec:
                            inst_in[nm] = link_spec[lid]
                        elif nm in named:
                            inst_in[nm] = ("lit", named[nm])
                    pin_names: Dict[Any, str] = {}
                    slot_names: List[str] = []
                    for pin in sg.get("inputs") or []:
                        slot_names.append(pin.get("name"))
                        for lid in (pin.get("linkIds") or []):
                            pin_names[lid] = pin.get("name")
                    iid = (sg.get("inputNode") or {}).get("id")
                    oid = (sg.get("outputNode") or {}).get("id")
                    inner_alias = walk(sg.get("nodes"), sg.get("links") or [], fid + ":", depth + 1,
                                       inst_in, pin_names, slot_names, iid, oid)
                    for slot, spec in inner_alias.items():
                        redirect[(fid, slot)] = spec
                    # 记录该 clip 的提示词节点（供 10 段提示词精确替换）
                    if "prompt" in inst_in:
                        clip_no = None
                        m = re.search(r"(\d+)", str(named.get("prompt", "")))
                        if m:
                            clip_no = int(m.group(1))
                        inst_records.append((len(inst_records), clip_no, fid, inst_in["prompt"]))
                    continue

                # 2) 子图内部虚拟输入/输出节点
                if (inode is not None and nid == inode) or (onode is not None and nid == onode):
                    continue

                # 3) Set / Get / Reroute / PrimitiveNode → 重定向
                if ntype == "SetNode":
                    nm = named.get("Constant")
                    src = None
                    for inp in raw.get("inputs") or []:
                        if inp.get("link") in link_spec:
                            src = link_spec[inp["link"]]
                            break
                    if nm is not None and src is not None:
                        set_map[nm] = src
                    continue
                if ntype == "GetNode":
                    nm = named.get("Constant")
                    if nm in set_map:
                        redirect[(fid, 0)] = set_map[nm]
                    else:
                        warnings.append(f"GetNode {fid} 引用了未定义变量 {nm!r}")
                        redirect[(fid, 0)] = ("lit", None)
                    continue
                if ntype == "Reroute":
                    for inp in raw.get("inputs") or []:
                        if inp.get("link") in link_spec:
                            redirect[(fid, 0)] = link_spec[inp["link"]]
                            break
                    continue
                if ntype == "PrimitiveNode":
                    vals = [v for v in (raw.get("widgets_values") or []) if v is not None]
                    redirect[(fid, 0)] = ("lit", vals[0] if vals else None)
                    continue
                if ntype in VIRTUAL_NODE_TYPES:
                    continue

                # 4) 真实节点
                flat[fid] = {"type": ntype, "named": named, "seq": seq[0]}
                seq[0] += 1
                for inp in raw.get("inputs") or []:
                    nm, lid = inp.get("name"), inp.get("link")
                    if nm is None or lid is None or lid not in link_spec:
                        continue
                    spec = link_spec[lid]
                    # 子图内部：该输入来自子图外部绑定
                    if inode is not None and spec[1] == f"{prefix}{inode}":
                        bind_name = in_link_names.get(lid)
                        if bind_name is None and in_slot_names and spec[2] < len(in_slot_names):
                            bind_name = in_slot_names[spec[2]]
                        spec = (in_bindings or {}).get(bind_name, ("lit", None))
                    pending.append((fid, nm, spec))

            # 子图输出槽位 → 本层真实来源
            if onode is not None:
                for l in links or []:
                    if isinstance(l, dict) and l.get("target_id") == onode:
                        out_alias[l.get("target_slot", 0)] = (
                            "node", f"{prefix}{l.get('origin_id')}", l.get("origin_slot", 0))
                    elif isinstance(l, (list, tuple)) and len(l) >= 5 and l[3] == onode:
                        out_alias[l[4]] = ("node", f"{prefix}{l[1]}", l[2])
            return out_alias

        walk(ui_workflow.get("nodes") or [], ui_workflow.get("links") or [], "", 0,
             {}, {}, [], None, None)

        # ---------- 取值解析（跟随重定向链） ----------

        def resolve(spec, depth=0):
            if spec is None or depth > 16:
                return None
            if spec[0] == "lit":
                return spec
            if (spec[1], spec[2]) in redirect:
                return resolve(redirect[(spec[1], spec[2])], depth + 1)
            if spec[1] not in flat:
                return None
            return spec

        # 位置兜底所需的控件名（object_info 不可用时退化为 inputs 里的 widget 项）
        def fallback_widgets(raw):
            named = raw.get("widgets_values_named") or {}
            if named:
                return dict(named)
            widget_names = [i.get("name") for i in (raw.get("inputs") or []) if "widget" in i]
            values = list(raw.get("widgets_values") or [])
            if len(values) > len(widget_names):
                # 剔除伪控件取值（如 seed 后的 'randomize'）
                values = [v for idx, v in enumerate(values)
                          if not (idx > 0 and isinstance(v, str) and v in PSEUDO_VALUES)]
            while len(values) > len(widget_names):
                values.pop()
            return dict(zip(widget_names, values))

        # 重新遍历原始节点树取得「未使用 named 的节点」的兜底控件值
        raw_nodes_by_id: Dict[str, dict] = {}

        def collect(nodes, prefix):
            for raw in nodes or []:
                fid = f"{prefix}{raw.get('id')}"
                raw_nodes_by_id[fid] = raw
                sg = subgraphs.get(raw.get("type") or "")
                if sg:
                    collect(sg.get("nodes"), fid + ":")

        collect(ui_workflow.get("nodes") or [], "")

        # ---------- 组装 API prompt ----------

        pending_by_node: Dict[str, List[tuple]] = {}
        for pid, nm, spec in pending:
            pending_by_node.setdefault(pid, []).append((nm, spec))

        api: Dict[str, dict] = {}
        unresolved: List[str] = []
        for fid, info in sorted(flat.items(), key=lambda kv: kv[1]["seq"]):
            named = info["named"]
            if not named and fid in raw_nodes_by_id:
                named = fallback_widgets(raw_nodes_by_id[fid])
            inputs: Dict[str, Any] = {}
            ctype = info["type"]
            for k, v in named.items():
                if k in PSEUDO_WIDGETS:
                    continue
                if isinstance(v, str) and ctype.startswith("Load") and k in MEDIA_INPUT_KEYS:
                    # P0-5：按节点「读取目录」规范化标注——Load*Output 必须带 " [output]"，
                    # LoadImage 等 input 目录节点写裸文件名（不得带标注）
                    v = self.annotate_file_ref(v, ctype)
                inputs[k] = v
            for nm, spec in pending_by_node.get(fid, []):
                r = resolve(spec)
                if r is None:
                    unresolved.append(f"{fid}.{nm}")
                    continue
                if r[0] == "lit":
                    inputs[nm] = r[1]
                else:
                    inputs[nm] = [r[1], r[2]]
            api[fid] = {"class_type": info["type"], "inputs": inputs}

        # clip → 提示词节点映射（解析后回填）
        clip_prompt_nodes: List[tuple] = []
        for order, clip_no, fid, spec in inst_records:
            r = resolve(spec)
            if r and r[0] == "node":
                clip_prompt_nodes.append((clip_no if clip_no is not None else order + 1, r[1]))
        clip_prompt_nodes.sort(key=lambda x: x[0])

        meta = {
            "flat_nodes": len(api),
            "subgraph_count": len(subgraphs),
            "clip_prompt_nodes": clip_prompt_nodes,
            "unresolved_inputs": unresolved,
            "warnings": warnings,
        }
        if unresolved:
            logger.warning(f"UI→API 转换存在未解析输入 {len(unresolved)} 个: {unresolved[:5]}")
        logger.info(f"UI→API 完成: 真实节点 {len(api)} 个, 子图 {len(subgraphs)} 个, "
                    f"clip→提示词节点 {clip_prompt_nodes}")
        return api, meta

    # ---------- 转换结果自检 ----------

    def validate_api_prompt(self, api_prompt: dict, verbose: bool = False) -> dict:
        """用 object_info 校验转换结果：未知节点类型 / 缺失必填输入 / 悬空连线"""
        oi = self.get_object_info()
        ids = set(api_prompt.keys())
        unknown_types, missing_required, dangling, unexpected = [], [], [], []
        for nid, node in api_prompt.items():
            ct = node.get("class_type")
            spec = (oi.get(ct) or {}).get("input") if oi else None
            if oi and ct not in oi:
                unknown_types.append(f"{nid}:{ct}")
            for k, v in (node.get("inputs") or {}).items():
                if isinstance(v, list) and len(v) == 2 and isinstance(v[0], str):
                    if v[0] not in ids:
                        dangling.append(f"{nid}.{k} -> {v[0]}")
                elif spec is not None:
                    if k not in ((spec.get("required") or {}) | (spec.get("optional") or {})):
                        unexpected.append(f"{nid}.{k}")
            if spec:
                for req in (spec.get("required") or {}).keys():
                    if req not in (node.get("inputs") or {}):
                        missing_required.append(f"{nid}({ct}).{req}")
        report = {
            "node_count": len(api_prompt),
            "unknown_types": unknown_types,
            "missing_required": missing_required,
            "dangling_links": dangling,
            "unexpected_inputs": unexpected,
        }
        if verbose or unknown_types or missing_required or dangling:
            logger.info(f"转换自检: {json.dumps(report, ensure_ascii=False)[:600]}")
        return report

    # ===================== 资源与队列 =====================

    def upload_image(self, image_path: str, name: str = None,
                     subfolder: str = "", image_type: str = "input") -> str:
        """上传图片到 ComfyUI（input / output / temp 目录）"""
        url = f"{self.base_url}/upload/image"
        if name is None:
            name = os.path.basename(image_path)
        with open(image_path, "rb") as f:
            files = {"image": (name, f, "image/png")}
            data = {"overwrite": "true", "type": image_type}
            if subfolder:
                data["subfolder"] = subfolder
            resp = requests.post(url, files=files, data=data, timeout=120)
            resp.raise_for_status()
            result = resp.json()
            uploaded = result.get("name", name)
            sub = result.get("subfolder") or ""
            return f"{sub}/{uploaded}" if sub else uploaded

    def queue_prompt(self, api_prompt: dict) -> str:
        payload = {"prompt": api_prompt, "client_id": self.client_id}
        try:
            result = self._post("/prompt", payload)
        except Exception:
            _bump("prompt_failed")
            raise
        if "error" in result:
            _bump("prompt_failed")
            raise RuntimeError(f"ComfyUI 队列错误: {result['error']}")
        _bump("prompt_submitted")
        return result.get("prompt_id", "")

    def get_history(self, prompt_id: str) -> dict:
        return self._get(f"/history/{prompt_id}")

    def wait_for_completion(self, prompt_id: str, timeout: int = 1800) -> dict:
        start = time.time()
        while time.time() - start < timeout:
            try:
                history = self.get_history(prompt_id)
                if prompt_id in history:
                    entry = history[prompt_id]
                    status = entry.get("status", {}) or {}
                    if status.get("completed") or status.get("status_str") == "success":
                        _bump("completed")
                        _bump("waited_seconds", round(time.time() - start, 2))
                        return entry
                    if status.get("status_str") == "error":
                        logger.error(f"生成出错: {status}")
                        _bump("waited_seconds", round(time.time() - start, 2))
                        return entry
            except Exception as e:
                logger.debug(f"轮询历史失败: {e}")
            time.sleep(3)
        logger.warning(f"等待超时: {prompt_id}")
        _bump("waited_seconds", round(time.time() - start, 2))
        return {}

    def get_output_files(self, history: dict, file_ext: str = "") -> List[str]:
        files = []
        for _node_id, node_output in (history.get("outputs") or {}).items():
            for _key, value in (node_output or {}).items():
                if not isinstance(value, list):
                    continue
                for item in value:
                    if isinstance(item, dict) and "filename" in item:
                        filename = item["filename"]
                        subfolder = item.get("subfolder", "")
                        base = os.path.join(COMFYUI_OUTPUT_DIR, subfolder) if subfolder else COMFYUI_OUTPUT_DIR
                        full = os.path.join(base, filename)
                        if not file_ext or filename.endswith(file_ext):
                            files.append(full)
        return files

    # ---------- 路径工具（P0-4：HTTP 资源路径 → 本地绝对路径） ----------

    @staticmethod
    def resolve_local_path(path_or_url: str) -> Optional[str]:
        """把前端传来的 HTTP 资源路径（/api/assets/...、/api/videos/...）解析为本地绝对路径"""
        if not path_or_url or not isinstance(path_or_url, str):
            return None
        p = path_or_url.strip()
        if p.startswith("http://") or p.startswith("https://"):
            # 去掉协议与主机，仅保留路径部分
            rest = p.split("//", 1)[-1]
            p = "/" + rest.split("/", 1)[1] if "/" in rest else "/"
        p = p.replace("\\", "/")
        if p.startswith("/api/assets/"):
            return os.path.normpath(os.path.join(PROJECT_OUTPUT_DIR, "assets", p[len("/api/assets/"):]))
        if p.startswith("/api/videos/"):
            return os.path.normpath(os.path.join(PROJECT_OUTPUT_DIR, "videos", p[len("/api/videos/"):]))
        if p.startswith("/api/final/"):
            return os.path.normpath(os.path.join(PROJECT_OUTPUT_DIR, "final", p[len("/api/final/"):]))
        if p.startswith("/api/storyboards/file/"):
            return os.path.normpath(os.path.join(PROJECT_OUTPUT_DIR, "storyboards",
                                                 p[len("/api/storyboards/file/"):]))
        if os.path.exists(p):
            return os.path.normpath(p)
        return None

    # ---------- 目录标注工具（P0-5：按节点类型区分 [output] / 无标注） ----------

    @staticmethod
    def annotate_file_ref(filename: str, class_type: str, default_dir: str = ANNOTATED_DIR) -> str:
        """按「读取目录」语义为文件名型资源输入补/去目录标注。

        - Load*Output 系列（LoadImageOutput / LoadAudioOutput / ...）读 ComfyUI output 目录
          → 返回 "名字 [output]"
        - LoadImage / LoadAudio / LoadVideo 等读 input 目录 → 返回 "名字"（不带标注）
        - 其它类型 → 原样返回，不做任何加工（避免引入新错误）
        """
        if not filename or not isinstance(filename, str):
            return filename
        name = SUFFIX_RE.sub("", filename).strip()   # 先剥离可能已存在的标注，保证幂等
        if class_type in OUTPUT_LOAD_CLASSES or \
                (class_type.startswith("Load") and class_type.endswith("Output")):
            return f"{name} [{default_dir}]"
        if class_type in INPUT_LOAD_CLASSES or class_type.startswith("Load"):
            return name
        return filename

    # ===================== 第一阶段：基础图生成 =====================

    # ---------- P0 修复辅助：场景去人 / 冲突负向词清理 ----------

    @classmethod
    def clean_conflict_negative_tokens(cls, api_prompt: dict) -> dict:
        """从负向提示词槽位剔除与正向 3D 风格冲突的词（P0：风格冲突）

        只处理判定为负向的槽位（含 NEGATIVE_HINTS 之一），不改正向提示词。
        返回 {节点id: 变更说明} 便于审计。
        """
        changed: dict = {}
        for nid, node in (api_prompt or {}).items():
            if not isinstance(node, dict):
                continue
            if str(node.get("class_type") or "") not in ("CLIPTextEncode", "TextEncodeQwenImageEditPlus"):
                continue
            inputs = node.get("inputs") or {}
            for field in PROMPT_TEXT_FIELDS:
                value = inputs.get(field)
                if not isinstance(value, str) or not value.strip():
                    continue
                low = value.lower()
                if not any(h.lower() in low for h in NEGATIVE_HINTS):
                    continue    # 正向槽位不动
                new = value
                removed: List[str] = []
                for tok in CONFLICT_NEGATIVE_SORTED:
                    if tok in new:
                        new = new.replace(tok, "")
                        removed.append(tok)
                if not removed:
                    continue
                new = re.sub(r"[，,、]\s*(?=[，,、])", "", new)
                new = re.sub(r"^\s*[，,、]+\s*", "", new)
                new = re.sub(r"[，,、\s]+$", "", new)
                inputs[field] = new
                changed[str(nid)] = f"{field}: 移除冲突负向词 {removed}"
        if changed:
            logger.info(f"[风格冲突清理] 负向提示词已修正 {len(changed)} 处: {changed}")
        return changed

    @classmethod
    def sanitize_scene_prompt(cls, prompt_zh: str) -> str:
        """场景提示词去人物（P0：场景资产带人）

        场景定义常写「村民三两结伴」→ 资产图实测渲染出 4 人。这里按分句粒度丢弃含人物
        描述的短句，并追加空场景声明；若清洗后为空则回退原文（避免把场景描述清空）。
        """
        text = (prompt_zh or "").strip()
        if not text:
            return text
        parts = [p.strip() for p in _PROMPT_SPLIT_RE.split(text)]
        kept: List[str] = []
        dropped: List[str] = []
        for p in parts:
            if not p:
                continue
            hit = any(w in p for w in CHARACTER_WORDS) or bool(CHARACTER_QTY_RE.search(p))
            if hit:
                dropped.append(p)
            else:
                kept.append(p)
        cleaned = "，".join(kept).strip()
        if not cleaned:
            cleaned = text      # 全句含人物时不至于清空，仅靠正向声明压制
        if dropped:
            logger.info(f"[场景去人] 丢弃人物描述句 {dropped}；清洗后场景描述: {cleaned[:80]}")
        return cleaned.rstrip("。;； ") + SCENE_NO_CHARACTER_SUFFIX

    @staticmethod
    def _harden_no_watermark(api_prompt: dict) -> dict:
        """C 项⑧：图片生成链路彻底去水印（仅改内存中的 API prompt，不动工作流文件）

        对每个提示词节点（CLIPTextEncode / TextEncodeQwenImageEditPlus）：
        - 该槽位是负向提示词 → 追加水印类排除词；
        - 该槽位是正向提示词 → 追加「画面干净、无任何水印/文字」声明。
        幂等：已包含则不重复追加。
        返回 {节点id: 变更说明} 便于日志审计。
        """
        changed = {}
        for nid, node in (api_prompt or {}).items():
            if not isinstance(node, dict):
                continue
            ctype = str(node.get("class_type") or "")
            if ctype not in ("CLIPTextEncode", "TextEncodeQwenImageEditPlus"):
                continue
            inputs = node.get("inputs") or {}
            for field in PROMPT_TEXT_FIELDS:
                value = inputs.get(field)
                if not isinstance(value, str) or not value.strip():
                    continue
                # 幂等：已加固过的槽位直接跳过（否则正向后缀里的"水印"二字会被误判为负向）
                if NO_WATERMARK_POSITIVE_SUFFIX in value or NO_WATERMARK_NEGATIVE_EXTRA in value:
                    continue
                low = value.lower()
                is_negative = any(h.lower() in low for h in NEGATIVE_HINTS)
                if is_negative:
                    if NO_WATERMARK_NEGATIVE_EXTRA in value:
                        continue
                    inputs[field] = value.rstrip("，,;； ") + ", " + NO_WATERMARK_NEGATIVE_EXTRA
                    changed[str(nid)] = f"{field}: 负向追加水印排除词"
                else:
                    if NO_WATERMARK_POSITIVE_SUFFIX in value:
                        continue
                    inputs[field] = value.rstrip("。;； ") + NO_WATERMARK_POSITIVE_SUFFIX
                    changed[str(nid)] = f"{field}: 正向追加无水印声明"
        if changed:
            logger.info(f"[去水印强化] 图片提示词已加固 {len(changed)} 处: {changed}")
        return changed

    @classmethod
    def harden_video_no_text(cls, api_prompt: dict, node_ids=None) -> dict:
        """H3 视频链路：向提示词节点追加「画面内不得出现文字/字幕」声明

        H3 工作流的提示词节点是纯文本节点（Text Multiline），不在图片链路的
        CLIPTextEncode / TextEncodeQwenImageEditPlus 白名单内，故单独处理。
        仅改内存中的 API prompt，不动磁盘工作流文件；幂等（含声明则跳过）。
        """
        changed = {}
        targets = [str(n) for n in (node_ids if node_ids is not None else list(api_prompt or {}))]
        for nid in targets:
            node = (api_prompt or {}).get(str(nid))
            if not isinstance(node, dict):
                continue
            ctype = str(node.get("class_type") or "")
            if ctype not in VIDEO_PROMPT_NODE_TYPES:
                continue
            inputs = node.get("inputs") or {}
            for field in PROMPT_TEXT_FIELDS:
                value = inputs.get(field)
                if not isinstance(value, str) or not value.strip():
                    continue
                if VIDEO_NO_TEXT_SUFFIX in value:
                    continue
                inputs[field] = value.rstrip("。;；\n ") + VIDEO_NO_TEXT_SUFFIX
                changed[str(nid)] = f"{field}: 追加无文字/字幕声明"
        if changed:
            logger.info(f"[H3 无字幕强化] 视频提示词已加固 {len(changed)} 处: {changed}")
        return changed

    def _find_positive_text_node(self, api_prompt: dict, class_types=("CLIPTextEncode",)) -> Optional[str]:
        """在提示词编码节点中定位正向节点（不含负向关键词者）"""
        candidates = []
        for nid, node in api_prompt.items():
            if node.get("class_type") not in class_types:
                continue
            texts = [str(v) for v in (node.get("inputs") or {}).values() if isinstance(v, str)]
            joined = " ".join(texts).lower()
            if not any(h.lower() in joined for h in NEGATIVE_HINTS):
                candidates.append(nid)
        if not candidates:
            # 全部命中负向词时，退化为「id 最大的那个」
            pool = [nid for nid, n in api_prompt.items() if n.get("class_type") in class_types]
            return sorted(pool, key=lambda x: int(x) if str(x).isdigit() else 0)[-1] if pool else None
        # 正向通常有多个文本槽（如 prompt/image1..3），取最后一个可用候选
        return sorted(candidates, key=lambda x: int(x) if str(x).isdigit() else 0)[-1]

    def _generate_base_image(self, workflow_file: str, prompt_zh: str,
                             asset_type: str = None, seed: int = None) -> List[str]:
        """通用基础图生成：更新正向提示词节点

        P0 修复（同轮补充）：
        - asset_type="scene" → 清洗人物描述并追加"空场景"声明（场景资产不得带人）；
        - clean_conflict_negative_tokens 剔除与 3D 正向风格冲突的负向词；
        - seed 用于质检不达标时的重生成（保证与上一版结果不同）。
        """
        api_prompt, meta = self.load_workflow(workflow_file, return_meta=True)
        node_id = self._find_positive_text_node(api_prompt)
        if node_id is None:
            logger.error(f"{workflow_file} 中未找到正向提示词节点，转换元信息: {meta}")
            return []
        # 场景资产去人
        if asset_type == "scene":
            prompt_zh = self.sanitize_scene_prompt(prompt_zh)
        node = api_prompt[node_id]
        if "text" in node["inputs"]:
            node["inputs"]["text"] = prompt_zh
        else:
            # TextEncodeQwenImageEditPlus 等使用 prompt 字段
            for k, v in list(node["inputs"].items()):
                if isinstance(v, str):
                    node["inputs"][k] = prompt_zh
        logger.info(f"[{workflow_file}] 正向提示词节点 {node_id} 已更新（共 {len(api_prompt)} 节点）")
        self.clean_conflict_negative_tokens(api_prompt)                 # P0：清理风格冲突负向词
        if seed is not None:
            logger.info(f"资产采样种子已注入: {self._inject_seed(api_prompt, seed)}")
        self._harden_no_watermark(api_prompt)   # C 项⑧：图片一律去水印

        prompt_id = self.queue_prompt(api_prompt)
        history = self.wait_for_completion(prompt_id)
        return self.get_output_files(history, ".png")

    def generate_character_base(self, prompt_zh: str, seed: int = None) -> List[str]:
        logger.info(f"生成角色基础图: {prompt_zh[:50]}...")
        return self._generate_base_image(WORKFLOW_TEMPLATE["character_gen"], prompt_zh,
                                         asset_type="character", seed=seed)

    def generate_item_base(self, prompt_zh: str, seed: int = None) -> List[str]:
        logger.info(f"生成物品基础图: {prompt_zh[:50]}...")
        return self._generate_base_image(WORKFLOW_TEMPLATE["item_gen"], prompt_zh,
                                         asset_type="item", seed=seed)

    def generate_scene_base(self, prompt_zh: str, seed: int = None) -> List[str]:
        logger.info(f"生成场景基础图: {prompt_zh[:50]}...")
        return self._generate_base_image(WORKFLOW_TEMPLATE["scene_gen"], prompt_zh,
                                         asset_type="scene", seed=seed)

    # ===================== 第二阶段：多视角生成 =====================

    def generate_multiview(self, base_image_path: str, asset_type: str,
                           asset_name: str, base_prompt_zh: str,
                           seed: int = None) -> Dict[str, str]:
        """基于基础图生成多视角图（Qwen Edit 2511）

        character → 4 视图（正/左/右/背）；item / scene → 4 视角（正/左45/右45/俯视）
        P0 修复：正向提示词统一补「竖屏 9:16」画幅声明（base 图已是竖屏 → 多视角保持竖屏）；
        seed 供 app 层质检不达标时重生成。
        """
        views = MULTIVIEW_CONFIG["character_views"] if asset_type == "character" \
            else MULTIVIEW_CONFIG["item_scene_views"]

        # 基础图必须进入 ComfyUI output 目录（分镜生成.json 用的是 LoadImageOutput）
        base_name = f"comic_drama_{asset_type}_{asset_name}_base.png"
        try:
            output_name = self.upload_image(base_image_path, base_name, image_type="output")
        except Exception as e:
            # 不做「回退到 input 目录」：LoadImageOutput 只认 output 目录，回退必然 400，
            # 与其提交注定失败的 prompt，不如快速失败并给出明确原因（P0-5）
            raise RuntimeError(
                f"基础图上传到 ComfyUI output 目录失败，LoadImageOutput 无法引用: {e}"
            ) from e
        logger.info(f"基础图已上传到 ComfyUI output 目录: {output_name}")

        # P0：场景多视角同样必须去人（基础图与多视角一致，避免视角转换时"带出"人物）
        if asset_type == "scene":
            base_prompt_zh = self.sanitize_scene_prompt(base_prompt_zh)

        results = {}
        for view in views:
            logger.info(f"生成 {asset_name} {view['label']}...")
            view_prompt = self._build_multiview_prompt(asset_type, base_prompt_zh, view)
            if asset_type == "scene" and SCENE_NO_CHARACTER_SUFFIX not in view_prompt:
                view_prompt = view_prompt.rstrip("。;； ") + SCENE_NO_CHARACTER_SUFFIX
            img_path = self._run_multiview_workflow(output_name, view_prompt, seed=seed)
            if img_path:
                results[view["key"]] = img_path
            else:
                logger.warning(f"{asset_name} {view['label']} 生成失败")
        return results

    def _build_multiview_prompt(self, asset_type: str, base_desc: str, view: dict) -> str:
        camera_terms = f"{view['azimuth']}, {view['elevation']}, {view['distance']}"
        if asset_type == "character":
            return (
                f"根据参考图生成同一角色的{view['label']}视图，"
                f"保持人物的脸型、发型、服装、配饰与参考图完全一致，"
                f"仅改变观察角度。{camera_terms}。{base_desc}"
            )
        asset_word = "物品" if asset_type == "item" else "场景"
        return (
            f"根据参考图生成同一{asset_word}的{view['label']}3D多视角图，"
            f"保持{asset_word}的形状、材质、颜色与参考图完全一致，"
            f"3D渲染视角转换。{camera_terms}。{base_desc}"
        )

    def _run_multiview_workflow(self, uploaded_image_name: str, prompt_zh: str,
                                image_dir: str = ANNOTATED_DIR,
                                seed: int = None) -> Optional[str]:
        """运行多视角编辑工作流（分镜生成.json：Qwen Edit 2511）"""
        api_prompt, meta = self.load_workflow(WORKFLOW_TEMPLATE["multiview_gen"], return_meta=True)
        if seed is not None:
            logger.info(f"多视角采样种子已注入: {self._inject_seed(api_prompt, seed)}")

        # 1) 正向提示词（TextEncodeQwenImageEditPlus：prompt 字段）
        node_id = self._find_positive_text_node(api_prompt, class_types=("TextEncodeQwenImageEditPlus",))
        if node_id is not None:
            api_prompt[node_id]["inputs"]["prompt"] = prompt_zh
        else:
            logger.warning("分镜生成.json 未定位到正向提示词节点")
        self.clean_conflict_negative_tokens(api_prompt)   # P0：清理风格冲突负向词
        self._harden_no_watermark(api_prompt)   # C 项⑧：图片一律去水印

        # 2) 参考图：3 个 LoadImageOutput 全部替换（P0-3），且按节点类型补目录标注（P0-5）
        #    LoadImageOutput 读 output 目录 → 必须写 "名字 [output]"
        #    LoadImage（若模板中出现）读 input 目录 → 必须写裸文件名，不能带标注
        ref_nodes = [(nid, n.get("class_type")) for nid, n in api_prompt.items()
                     if n.get("class_type") in ("LoadImageOutput", "LoadImage")]
        ref_values = []
        for nid, ctype in ref_nodes:
            value = self.annotate_file_ref(uploaded_image_name, ctype, default_dir=image_dir)
            api_prompt[nid]["inputs"]["image"] = value
            ref_values.append(f"{nid}({ctype})={value}")
        if not ref_nodes:
            logger.warning("分镜生成.json 中未找到参考图节点")
        else:
            logger.info(f"多视角参考图已替换 {len(ref_nodes)} 个节点: {ref_values}")

        prompt_id = self.queue_prompt(api_prompt)
        history = self.wait_for_completion(prompt_id, timeout=900)
        files = self.get_output_files(history, ".png")
        return files[0] if files else None

    # ===================== 第三阶段：分镜图生成（Qwen Edit 2511） =====================

    @staticmethod
    def _find_image_slots(api_prompt: dict, prompt_node_id: str) -> List[Tuple[str, Optional[str]]]:
        """解析正向编辑节点的 image1/image2/image3 … 槽位 → 真正持有文件名的 LoadImage* 节点 id

        分镜生成.json 的链路为：
            LoadImageOutput(读 output 目录) → FluxKontextImageScale → TextEncodeQwenImageEditPlus.imageN
        因此需沿链路向上游回溯一层，拿到 LoadImage* 节点，才能替换参考图。
        """
        result: List[Tuple[str, Optional[str]]] = []
        node = api_prompt.get(prompt_node_id) or {}
        keys = sorted((k for k in (node.get("inputs") or {}) if re.fullmatch(r"image\d*", str(k))),
                      key=lambda k: int(re.sub(r"\D", "", str(k)) or 0))
        for key in keys:
            value = node["inputs"][key]
            load_id: Optional[str] = None
            if isinstance(value, list) and len(value) == 2:
                src = api_prompt.get(str(value[0])) or {}
                if str(src.get("class_type", "")).startswith("LoadImage"):
                    load_id = str(value[0])
                else:
                    for _k, v in (src.get("inputs") or {}).items():
                        if isinstance(v, list) and len(v) == 2:
                            cand = api_prompt.get(str(v[0])) or {}
                            if str(cand.get("class_type", "")).startswith("LoadImage"):
                                load_id = str(v[0])
                                break
            result.append((key, load_id))
        return result

    @staticmethod
    def build_storyboard_prompt(shot: dict, ref_labels: List[str] = None) -> str:
        """按镜头剧情描述构建分镜图（Qwen Edit 多参考图）中文提示词"""
        parts = ["根据参考图生成漫剧分镜画面。"]
        if ref_labels:
            parts.append("参考图用途：" + "；".join(ref_labels) + "。")
        location = shot.get("location", "")
        camera = str(shot.get("camera") or "中景").strip()
        cam_spec = SHOT_CAMERA_SPECS.get(camera) or SHOT_CAMERA_SPECS["中景"]
        desc = (shot.get("description") or "").strip()
        parts.append(
            f"镜头{shot.get('shot_id', 1)}。**景别（必须严格遵守）：{camera}**——{cam_spec}。"
            + (f"场景：{location}。" if location else "")
            + (f"动作与画面内容：{desc}{SHOT_ACTION_SUFFIX}。" if desc else "")
        )
        if _dlg_text(shot.get("dialogue")):
            # 只给说话状态与口型提示，严禁把台词文本写进提示词（模型会把台词当画面字幕画出来）
            parts.append(
                f"说话状态：{_dlg_speaker(shot.get('dialogue')) or '人物'}正在低声说一句短句，"
                f"只表现为自然的口型开合与细微表情变化。"
            )
        if shot.get("emotion"):
            parts.append(f"情绪氛围：{shot['emotion']}。")
        parts.append(
            "要求：画面中人物的脸型、发型、服装、配饰与角色参考图完全一致，"
            "物品的形状、材质、颜色与物品参考图一致，环境氛围与场景参考图一致；"
            "竖屏 9:16 构图，国漫3D渲染风格，"
            "光影细腻，构图清晰；镜头景别必须与上述规定一致，"
            "画面中不得出现任何文字、字幕、台词文本、水印、logo 或标识"
            "（尤其不得在右下角出现「AI生成」等生成标识）。"
        )
        return "".join(parts)

    # ===================== H3 音轨控制（生成阶段不出声，配音统一交给 QwenTTS） =====================

    # 末端封装/保存节点：只有这些节点决定最终落盘文件是否带音轨。
    # 说明：H3 工作流内部还有 H3ContinuousStitchOutputV14 等带 audio 输入的中间节点（audio 为
    # optional），它们承担 10 段之间的音频接力；这里**不切断中间节点**，避免破坏连续段链路，
    # 也避免产出"静音但仍有音频流"的伪无声文件。真正不产生音轨靠切断末端 mux 节点实现。
    H3_AUDIO_MUX_TYPES = ("CreateVideo", "CreateVideoWithAudio", "SaveVideo",
                          "SaveWEBM", "VHS_VideoCombine", "SaveAudio", "CreateAudio")
    # 兼容旧命名（早期版本使用的属性名）
    H3_AUDIO_SINK_TYPES = H3_AUDIO_MUX_TYPES

    @classmethod
    def strip_h3_audio_inputs(cls, api_prompt: dict) -> List[str]:
        """断开 H3 工作流末端封装节点的音频输入，使输出 mp4 不含音轨

        仅改动本次提交的 API prompt（内存对象），不修改磁盘上的工作流文件。
        返回被改写的节点描述列表，便于日志核对。
        """
        changed: List[str] = []
        for nid, node in (api_prompt or {}).items():
            if not isinstance(node, dict):
                continue
            ctype = str(node.get("class_type") or "")
            if ctype not in cls.H3_AUDIO_SINK_TYPES:
                continue
            inputs = node.get("inputs") or {}
            for key in ("audio", "audio1", "audio2", "audio_path", "audio_input"):
                if key in inputs and inputs.get(key) is not None:
                    old = inputs[key]
                    inputs[key] = None
                    changed.append(f"{nid}({ctype}).{key}=None(原={old})")
        return changed

    # ===================== 随机种子注入（质检重试时用于产出不同结果） =====================

    @staticmethod
    def _inject_seed(api_prompt: dict, seed) -> List[str]:
        """把 seed 写入工作流中所有采样类节点的 seed / noise_seed 输入

        返回被改写的节点描述列表（便于日志核对）。未传 seed 或未找到采样节点时不做任何改动。
        """
        if seed is None:
            return []
        changed: List[str] = []
        for nid, node in (api_prompt or {}).items():
            if not isinstance(node, dict):
                continue
            inputs = node.get("inputs") or {}
            ctype = str(node.get("class_type") or "")
            for key in ("seed", "noise_seed"):
                if key in inputs and not isinstance(inputs.get(key), list):
                    inputs[key] = int(seed)
                    changed.append(f"{nid}({ctype}).{key}={int(seed)}")
                    break
        return changed

    def generate_storyboard(self, prompt_zh: str, ref_images: List[str],
                            filename_prefix: str = "comic_drama_sb/shot",
                            seed: int = None, timeout: int = 900) -> dict:
        """使用 分镜生成.json（Qwen Edit 2511）生成单张分镜图

        ref_images: 参考图列表（本地绝对路径或 /api/... HTTP 资源路径），最多 3 张，
                    按顺序对应正向节点的 image1 / image2 / image3 槽位。
        seed:       可选随机种子（质检不达标重生成时传入，保证产出与上一次不同）。
        """
        api_prompt, _meta = self.load_workflow(WORKFLOW_TEMPLATE["storyboard_gen"], return_meta=True)
        seed_changed = self._inject_seed(api_prompt, seed)
        if seed_changed:
            logger.info(f"分镜采样种子已注入: {seed_changed}")

        # 1) 正向提示词
        node_id = self._find_positive_text_node(api_prompt, class_types=("TextEncodeQwenImageEditPlus",))
        if node_id is None:
            raise RuntimeError("分镜生成.json 未定位到正向提示词节点（TextEncodeQwenImageEditPlus）")
        api_prompt[node_id]["inputs"]["prompt"] = prompt_zh
        self.clean_conflict_negative_tokens(api_prompt)                 # P0：清理风格冲突负向词
        self._harden_no_watermark(api_prompt)   # C 项⑧：分镜图一律去水印

        # 2) 参考图上传到 ComfyUI output 目录（LoadImageOutput 只认 output 目录 + [output] 标注）
        uploaded: List[str] = []
        for idx, p in enumerate((ref_images or [])[:3]):
            local = self.resolve_local_path(p) if isinstance(p, str) else None
            if not local or not os.path.exists(local):
                logger.warning(f"分镜参考图不可用，已跳过: {p}")
                continue
            name = f"sb_ref_{os.path.splitext(os.path.basename(filename_prefix))[0]}_{idx + 1}.png"
            uploaded.append(self.upload_image(local, name, image_type="output"))
        if not uploaded:
            raise RuntimeError("分镜参考图全部不可用（请先完成步骤2/3/4的资产生成）")

        # 3) 逐个槽位替换参考图（不替换会残留模板里的他人图片名 → 400 Invalid image file）
        #    P0 修复（原 comfyui_client.py:870）：原实现 `uploaded[min(idx, len(uploaded) - 1)]`
        #    在参考图少于槽位时会把**最后一张**复制到所有多余槽位 —— ref_count=2（主角+场景）
        #    时 image3 变成第二张场景图，等于告诉模型"第三主体是场景"，造成主体错位/画面错乱。
        #    现改为：参考图与槽位按序一一对应；槽位多于参考图时，多余槽位复用**第一张
        #    （主角锚点）**，并在 slot_duplicates 中显式登记 + 日志告警，杜绝静默重复场景图。
        slots = self._find_image_slots(api_prompt, node_id)
        ref_values = []
        slot_duplicates: List[str] = []
        for idx, (key, load_id) in enumerate(slots):
            if load_id is None:
                continue
            if idx < len(uploaded):
                src = uploaded[idx]
            else:
                src = uploaded[0]
                slot_duplicates.append(f"{key}(slot{idx + 1})={src}")
                logger.warning(
                    f"分镜参考图槽位多于参考图（{len(slots)} 槽 / {len(uploaded)} 张）："
                    f"{key} 复用主角锚点图 {src}（已登记 slot_duplicates）")
            ctype = api_prompt[load_id].get("class_type")
            value = self.annotate_file_ref(src, ctype)
            api_prompt[load_id]["inputs"]["image"] = value
            ref_values.append(f"{key}->{load_id}({ctype})={value}")
        if slot_duplicates:
            logger.warning(f"分镜参考图存在槽位复用 {len(slot_duplicates)} 处: {slot_duplicates}")
        logger.info(f"分镜参考图已注入 {len(ref_values)} 个槽位: {ref_values}")

        # 4) 输出文件名前缀
        for _nid, n in api_prompt.items():
            if n.get("class_type") in ("SaveImageAdvanced", "SaveImage") and "filename_prefix" in n["inputs"]:
                n["inputs"]["filename_prefix"] = filename_prefix

        report = self.validate_api_prompt(api_prompt)
        if report["unknown_types"] or report["missing_required"] or report["dangling_links"]:
            logger.warning(f"分镜提交前自检异常: {json.dumps(report, ensure_ascii=False)[:400]}")

        prompt_id = self.queue_prompt(api_prompt)
        history = self.wait_for_completion(prompt_id, timeout=timeout)
        files = self.get_output_files(history, ".png")
        return {"prompt_id": prompt_id, "files": files, "history": history,
                "refs_used": uploaded, "prompt_node": node_id, "seed": seed,
                "slot_duplicates": slot_duplicates}

    # ===================== 视频生成（MiniMax H3） =====================

    def generate_video(self, prompt: str, reference_images: List[str] = None,
                       clip_prompts: List[str] = None,
                       filename_prefix: str = "comic_drama/shot",
                       emit_audio: bool = None,
                       seed: int = None, timeout: int = 1800) -> dict:
        """[LEGACY · 已停用] 固定 10 段模板的单次生成，语义为"一次产出 10 段拼接长视频"。

        ⚠️ 不再用于分镜视频生成：逐镜头调用它会导致"每个分镜跑 10 段"。
        请改用 generate_h3_sequence()——工作流段数 = 传入分镜数（1 段/镜 或 整集 N 段）。

        prompt:          单镜头提示词。H3 工作流的 10 段 Text Multiline 会**全部**替换为该提示词。
        clip_prompts:    可选，按 clip 序号提供 10 段不同提示词（不足则循环补足）。
        reference_images: 参考图本地绝对路径列表（HTTP 资源路径会先解析为本地路径）。
        emit_audio:      是否保留 H3 原生音轨，None 表示用配置 H3_EMIT_AUDIO；
                         默认 False（生成阶段不带声音，后续统一由 QwenTTS 配音）。
        seed:            可选随机种子（质检不达标重生成时传入，保证产出与上一次不同）。
        """
        api_prompt, meta = self.load_workflow(WORKFLOW_TEMPLATE["h3_video"], return_meta=True)
        seed_changed = self._inject_seed(api_prompt, seed)
        if seed_changed:
            logger.info(f"视频采样种子已注入: {seed_changed}")

        # 1) 参考图（P0-4：HTTP 路径 → 本地绝对路径）
        local_refs: List[str] = []
        for img in (reference_images or []):
            local = self.resolve_local_path(img)
            if local and os.path.exists(local):
                local_refs.append(local)
            else:
                logger.warning(f"参考图不可用，已跳过: {img}")
        if local_refs:
            uploaded = []
            for img in local_refs[:2]:
                try:
                    # 显式上传到 ComfyUI input 目录：H3 模板用 LoadImage（读 input），不带标注
                    uploaded.append(self.upload_image(img, image_type="input"))
                except Exception as e:
                    logger.warning(f"参考图上传失败 {img}: {e}")
            load_nodes = sorted([(nid, n.get("class_type")) for nid, n in api_prompt.items()
                                 if n.get("class_type") in ("LoadImage", "LoadImageOutput")],
                                key=lambda x: int(x[0]) if str(x[0]).isdigit() else 0)
            ref_values = []
            slot_duplicates: List[str] = []
            for idx, (nid, ctype) in enumerate(load_nodes):
                if not uploaded:
                    break
                # 按序一一对应；槽位多于参考图时复用第一张（主角锚点）并显式登记，杜绝静默重复场景图
                # （与 generate_storyboard 的 P0 修复保持一致）
                if idx < len(uploaded):
                    src = uploaded[idx]
                else:
                    src = uploaded[0]
                    slot_duplicates.append(f"{nid}({ctype})=复用第1张")
                    logger.warning(
                        f"H3 参考图槽位多于参考图（{len(load_nodes)} 槽 / {len(uploaded)} 张）："
                        f"{nid}({ctype}) 复用主角锚点图 {src}（已登记 slot_duplicates）")
                # 按节点类型区分：[output] 标注仅给 Load*Output 系列（P0-5）
                value = self.annotate_file_ref(src, ctype)
                api_prompt[nid]["inputs"]["image"] = value
                ref_values.append(f"{nid}({ctype})={value}")
            if slot_duplicates:
                logger.warning(f"H3 参考图存在槽位复用 {len(slot_duplicates)} 处: {slot_duplicates}")
            logger.info(f"H3 参考图已注入 {len(ref_values)} 个节点: {ref_values}")

        # 2) 提示词：10 段 Text Multiline 全部替换（P0-4 修复）
        clip_map: List[tuple] = meta.get("clip_prompt_nodes") or []
        if clip_map:
            targets = clip_map
        else:
            ml_ids = sorted([nid for nid, n in api_prompt.items()
                             if n.get("class_type") == "Text Multiline"],
                            key=lambda x: int(x) if str(x).isdigit() else 0)
            targets = [(i + 1, nid) for i, nid in enumerate(ml_ids)]
        if not targets:
            logger.warning("H3 工作流中未找到 Text Multiline 提示词节点")

        texts = list(clip_prompts) if clip_prompts else [prompt]
        for idx, (_clip_no, nid) in enumerate(targets):
            api_prompt[nid]["inputs"]["text"] = texts[idx] if idx < len(texts) else texts[-1]
        logger.info(f"H3 提示词已替换 {len(targets)} 段 Text Multiline（每段提示词 {len(texts)} 条）")

        # 3) 保存文件名前缀
        for nid, n in api_prompt.items():
            if n.get("class_type") in ("SaveVideo", "SaveImage", "SaveImageAdvanced", "VHS_VideoCombine"):
                if "filename_prefix" in n["inputs"]:
                    n["inputs"]["filename_prefix"] = filename_prefix

        # 4) 音轨策略：默认断开 CreateVideo 等封装节点的音频输入，成片不含音轨
        emit_audio = H3_EMIT_AUDIO if emit_audio is None else bool(emit_audio)
        audio_changed: List[str] = []
        if not emit_audio:
            audio_changed = self.strip_h3_audio_inputs(api_prompt)
            if audio_changed:
                logger.info(f"H3 音轨已断开（生成阶段不出声）: {audio_changed}")
            else:
                logger.warning("H3 音轨断开未命中任何节点，请检查工作流是否变更（成片可能仍带音轨）")
        else:
            logger.info("H3 音轨保留（emit_audio=True，按调用方要求）")

        report = self.validate_api_prompt(api_prompt)
        if report["unknown_types"] or report["missing_required"] or report["dangling_links"]:
            logger.warning(f"H3 提交前自检异常: {json.dumps(report, ensure_ascii=False)[:400]}")

        prompt_id = self.queue_prompt(api_prompt)
        history = self.wait_for_completion(prompt_id, timeout=timeout)
        files = self.get_output_files(history, ".mp4")

        # 5) 产物音轨复核（ffprobe 实测，不猜测）：应为无音频流
        audio_check = []
        if files:
            from video_postprocess import probe_media
            for f in files:
                m = probe_media(f)
                audio_check.append({"file": f, "has_audio": m.get("has_audio"),
                                    "audio_streams": m.get("audio_streams"),
                                    "video_streams": m.get("video_streams"),
                                    "error": m.get("error")})
            bad = [a for a in audio_check if a.get("has_audio")]
            if bad:
                logger.warning(f"H3 产物仍检测到音轨（未按预期静音）：{bad}")

        return {"prompt_id": prompt_id, "files": files, "history": history,
                "meta": meta, "seed": seed,
                "emit_audio": bool(emit_audio), "audio_disconnected": audio_changed,
                "audio_check": audio_check}

    # ===================== 视频生成（H3 · 动态段数：一个分镜一段） =====================

    def generate_h3_sequence(self, segments: List[dict],
                             filename_prefix: str = "comic_drama/episode",
                             emit_audio: bool = None,
                             seed: int = None,
                             timeout: int = None,
                             timeout_per_segment: int = 900,
                             template_file: str = None,
                             save_build_to: str = None) -> dict:
        """H3 多段一次生成：**工作流段数 = len(segments)**，一个分镜对应一段。

        与 generate_video 的差异（修复"每个分镜跑了 10 段"）：
        - 旧实现固定加载「10 段无缝拼接」模板，并把 10 段 Text Multiline 全部写成同一提示词，
          于是一个分镜产出的是 10 段同内容拼接的长视频（约 72s），既费时又不符合单镜时长。
        - 本方法按调用方给定的段数**动态重建工作流**（第 4 集 22 段、第 5 集 44 段），
          逐段独立注入 提示词 / 时长 / 参考图，段间仍由 H3ContinuousSeamlessJoinV14 保持无缝。

        segments: [{"prompt": str, "duration": float, "reference_images": [本地绝对路径, ...],
                    "name": str}]  —— 元素顺序 = 工作流段顺序
        timeout:  总超时（秒）；None 时按 1200 + timeout_per_segment × 段数 估算
        timeout_per_segment: 单段预估耗时（默认 900s，用于总超时兜底）
        save_build_to: 可选，把重建后的 UI 工作流落盘（便于复现/排障）
        """
        segs = [dict(s or {}) for s in (segments or [])]
        if not segs:
            raise ValueError("generate_h3_sequence: segments 不能为空")
        n = len(segs)
        tpl_name = template_file or WORKFLOW_TEMPLATE["h3_video"]
        tpl_path = os.path.join(COMFYUI_WORKFLOWS_DIR, tpl_name)
        builder = H3EpisodeBuilder(tpl_path)
        default_duration = float((segs[0] or {}).get("duration") or 5.0)
        wf, layout = builder.build(n, duration=default_duration)
        if save_build_to:
            os.makedirs(os.path.dirname(save_build_to), exist_ok=True)
            with open(save_build_to, "w", encoding="utf-8") as f:
                json.dump(wf, f, ensure_ascii=False)
            layout["build_path"] = save_build_to
        logger.info(f"H3 动态工作流已就绪：{n} 段（模板 {tpl_name}），"
                    f"UI 节点 {layout['node_total']} / 连线 {layout['link_total']}")

        api_prompt, meta = self.to_api(wf, return_meta=True)
        seed_changed = self._inject_seed(api_prompt, seed)
        if seed_changed:
            logger.info(f"视频采样种子已注入: {seed_changed}")

        # ---------------- 逐段注入（提示词 / 时长 / 参考图） ----------------
        seg_report: List[dict] = []
        for i, seg in enumerate(segs):
            lay = layout["segments"][i]
            prompt_text = seg.get("prompt") or ""
            api_prompt[str(lay["prompt_node"])]["inputs"]["text"] = prompt_text
            dur = float(seg.get("duration") or default_duration)
            api_prompt[str(lay["duration_node"])]["inputs"]["value"] = dur

            local_refs: List[str] = []
            for img in (seg.get("reference_images") or []):
                local = self.resolve_local_path(img)
                if local and os.path.exists(local):
                    local_refs.append(local)
                elif img:
                    logger.warning(f"段{i + 1} 参考图不可用，已跳过: {img}")
            loaded: List[dict] = []
            slots = lay["ref_nodes"]
            # 参考图不足时不再沿用模板自带的示例图（会污染角色外观），
            # 用本段第一张参考图补齐空槽（纯单参考即重复同一张）。
            fill_src = local_refs[0] if local_refs else None
            up_cache: dict = {}
            for j in range(len(slots)):
                is_fill = j >= len(local_refs)
                rp = local_refs[j] if not is_fill else fill_src
                if not rp:
                    logger.warning(f"段{i + 1} 无参考图，参考槽 {slots[j]} 沿用模板默认图")
                    continue
                try:
                    if rp not in up_cache:
                        # 参考图上传到 ComfyUI input 目录（段实例用 LoadImage 读取）
                        up_cache[rp] = self.annotate_file_ref(
                            self.upload_image(rp, image_type="input"), "LoadImage")
                    val = up_cache[rp]
                    api_prompt[str(slots[j])]["inputs"]["image"] = val
                    loaded.append({"slot": slots[j], "src": rp, "value": val})
                except Exception as e:
                    logger.warning(f"段{i + 1} 参考图上传失败 {rp}: {e}")
            seg_report.append({"index": i, "name": seg.get("name") or f"seg_{i + 1}",
                               "inst": lay["inst"], "prompt_len": len(prompt_text),
                               "prompt_head": prompt_text[:60], "duration": dur,
                               "refs": loaded})
            logger.info(f"段{i + 1}/{n} 注入完成：时长 {dur}s，参考图 {len(loaded)} 张")

        # ---------------- 保存文件名前缀 ----------------
        for nid, node in api_prompt.items():
            if node.get("class_type") in ("SaveVideo", "SaveImage", "SaveImageAdvanced", "VHS_VideoCombine"):
                if "filename_prefix" in node["inputs"]:
                    node["inputs"]["filename_prefix"] = filename_prefix

        # ---------------- 音轨策略（与 generate_video 一致：默认静音，后续统一配音） ----------------
        emit_audio = H3_EMIT_AUDIO if emit_audio is None else bool(emit_audio)
        audio_changed: List[str] = []
        if not emit_audio:
            audio_changed = self.strip_h3_audio_inputs(api_prompt)
            if audio_changed:
                logger.info(f"H3 音轨已断开（生成阶段不出声）: {audio_changed}")
            else:
                logger.warning("H3 音轨断开未命中任何节点，请检查工作流是否变更（成片可能仍带音轨）")

        self.clean_conflict_negative_tokens(api_prompt)   # P0：清理与 3D 正向风格冲突的负向词
        # 任务②：H3 提示词节点追加「画面内不得出现文字/字幕」声明（防台词被渲染成画面字幕）
        self.harden_video_no_text(api_prompt,
                                  [seg.get("prompt_node") for seg in layout["segments"]])

        report = self.validate_api_prompt(api_prompt)
        if report["unknown_types"] or report["missing_required"] or report["dangling_links"]:
            logger.warning(f"H3 提交前自检异常: {json.dumps(report, ensure_ascii=False)[:400]}")

        timeout = timeout or int(1200 + timeout_per_segment * n)
        logger.info(f"H3 提交：{n} 段，总超时 {timeout}s（单段预估 {timeout_per_segment}s）")
        prompt_id = self.queue_prompt(api_prompt)
        history = self.wait_for_completion(prompt_id, timeout=timeout)
        files = self.get_output_files(history, ".mp4")

        audio_check = []
        if files:
            from video_postprocess import probe_media
            for f in files:
                m = probe_media(f)
                audio_check.append({"file": f, "has_audio": m.get("has_audio"),
                                    "audio_streams": m.get("audio_streams"),
                                    "video_streams": m.get("video_streams"),
                                    "error": m.get("error")})

        return {"prompt_id": prompt_id, "files": files, "history": history,
                "segment_count": n, "segments": seg_report, "layout": layout,
                "meta": meta, "seed": seed, "emit_audio": bool(emit_audio),
                "audio_disconnected": audio_changed, "audio_check": audio_check,
                "timeout": timeout, "template": tpl_name,
                "validate_report": report}

    def _build_h3_prompt(self, shot: dict, char_refs: List[dict], scene_refs: List[dict],
                         storyboard_ref: dict = None) -> str:
        """构建 H3 Ref2VA 提示词（参考用户已验证的提示词结构）

        storyboard_ref 不为空时，参考图语义切换为：
            <Picture 1> = 该镜头的分镜图（画面构图 / 场景 / 人物姿态基准）
            <Picture 2> = 主角外观锚点
        """
        lines = ["subject_definitions:"]
        if storyboard_ref:
            sb_name = storyboard_ref.get("name") or "本镜头分镜图"
            lines.append(
                f"<Picture 1> is the storyboard keyframe of this shot, defining the "
                f"composition, framing, camera angle, environment and character pose."
            )
            main = (char_refs or [{}])[0]
            lines.append(
                f"<Picture 2> is the reference image defining the appearance, costume "
                f"and style of {main.get('name', '主角')}, and must stay consistent with <Picture 1>."
            )
            for i, ref in enumerate(char_refs[:1]):
                lines.append(f"<Subject {i + 1}> is {ref.get('name', '主角')} — {ref.get('appearance', '')}")
            lines.append("")
            lines.append("detailed_description:")
            lines.append(
                f"[镜头{shot.get('shot_id', 1)}, 0-{shot.get('duration', 5)}秒] "
                f"{shot.get('camera', '中景')}。以 <Picture 1> 分镜画面为构图基准，"
                f"保持场景、人物位置与动作一致，生成连贯动态镜头。"
                f"{(shot.get('description') or '').strip()}"
            )
            if _dlg_text(shot.get("dialogue")):
                # 只给说话状态提示，严禁把台词原文写进提示词（H3 会把它渲染成画面内字幕）
                lines.append(
                    f"说话状态：{_dlg_speaker(shot.get('dialogue')) or '人物'}正在低声说一句短句，"
                    f"仅表现为自然的口型开合与细微表情（情绪：{shot.get('emotion') or '平静'}）；"
                    f"画面中严禁出现任何文字、字幕、台词文本、水印或标识。"
                )
            lines.append(f"风格：{shot.get('style', '3D动漫渲染')}，画面流畅稳定，无畸形。")
            return "\n".join(lines)

        for i, ref in enumerate(char_refs[:2]):
            name = ref.get("name", f"角色{i + 1}")
            lines.append(
                f"<Picture {i + 1}> is the reference image defining the appearance, "
                f"costume and style of {name}, and serves as the composition anchor "
                f"for their on-screen shots."
            )
        scene_count = len(char_refs[:2])
        for i, ref in enumerate(scene_refs[:1]):
            name = ref.get("name", f"场景{i + 1}")
            lines.append(
                f"<Picture {scene_count + i + 1}> is the reference image defining "
                f"the environment and atmosphere of {name}."
            )
        for i, ref in enumerate(char_refs[:2]):
            name = ref.get("name", f"角色{i + 1}")
            appearance = ref.get("appearance", "")
            lines.append(f"<Subject {i + 1}> is {name} — {appearance}")

        lines.append("")
        lines.append("detailed_description:")
        lines.append(
            f"[镜头{shot.get('shot_id', 1)}, 0-{shot.get('duration', 5)}秒] "
            f"{shot.get('camera', '中景')}。{shot.get('description', '')}"
        )
        if _dlg_text(shot.get("dialogue")):
            # 只给说话状态提示，严禁把台词原文写进提示词（H3 会把它渲染成画面内字幕）
            lines.append(
                f"说话状态：{_dlg_speaker(shot.get('dialogue')) or '人物'}正在低声说一句短句，"
                f"仅表现为自然的口型开合与细微表情（情绪：{shot.get('emotion') or '平静'}）；"
                f"画面中严禁出现任何文字、字幕、台词文本、水印或标识。"
            )
        lines.append(f"风格：{shot.get('style', '3D动漫渲染')}，画面流畅稳定，无畸形。")
        return "\n".join(lines)
